[tool.isort]
known_testlib = "tests.testlib"
known_unittests = "tests.unit"
known_livestatus = "livestatus"
known_omd = "omdlib"
known_cmk_utils = "cmk.utils"
known_cmk_automations = "cmk.automations"
known_cmk_base = "cmk.base"
known_cmk_ec = "cmk.ec"
known_cmk_gui = "cmk.gui"
known_cmk_cee = "cmk.cee.dcd,cmk.cee.liveproxy,cmk.cee.mknotifyd"
known_cmk_notification_plugins = "cmk.notification_plugins"
known_cmk_snmplib = "cmk.snmplib"
known_cmk_core_helpers = "cmk.core_helpers"
known_first_party = "cmk"

# Order sections according to our layering.
sections = """FUTURE,STDLIB,THIRDPARTY,TESTLIB,UNITTESTS,LIVESTATUS,OMD,CMK_UTILS,CMK_AUTOMATIONS,
CMK_SNMPLIB,CMK_CORE_HELPERS,CMK_BASE,CMK_EC,CMK_GUI,CMK_CEE,CMK_NOTIFICATION_PLUGINS,FIRSTPARTY,
LOCALFOLDER"""

# configuration options compatible with black
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
order_by_type = "False"
line_length = 100
py_version = "310"


[tool.black]
line-length = 100
target-version = ['py310']


# NOTE: Keep this is sync with mypy-raw.ini!
[tool.mypy]
# When all of these are true, we can enable --strict
check_untyped_defs = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
disallow_untyped_defs = false
no_implicit_optional = true
no_implicit_reexport = false
strict_concatenate = false
strict_equality = true
warn_redundant_casts = false
warn_return_any = false
warn_unused_configs = false
warn_unused_ignores = false
# Miscellaneous stuff not in --strict
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_expr = false
disallow_any_unimported = false
warn_unreachable = false

[[tool.mypy.overrides]]
module = [
    "cmk.gui.plugins.views.mobile",
    "cmk.gui.plugins.views.layouts",
    "cmk.notification_plugins.*",
    "tests.gui_e2e.*",
    "tests.testlib.playwright.*",
    "tests.unit.cmk.ec.*",
    "tests.testlib.event_console",
]
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
